### ISSUE TITLE
Unable to install nextstrain environment under python 3.8

### ISSUE THREAD

**Issue by dnieuw** [nextstrain/conda#2]
Hi,

Your conda env yaml template lists python>=3.6* at http://data.nextstrain.org/nextstrain.yml, which is linked to in the manual (https://nextstrain.org/docs/getting-started/local-installation).

However the conda env does not build on python 3.8 (which it chose to install automatically).

Changing the python version to python=3.6* (without the >) fixed the problem for me.

**Comment by tsibley** [comment]
Hi @dnieuw, thanks for opening this issue! It appears that the file at <http://data.nextstrain.org/nextstrain.yml> drifted from the authoritative version here in this repo (which declares `python=3.6*`). I've corrected the drift and will look into why it happened.
