### ISSUE TITLE
Nextstrain Installation in centos7

### ISSUE THREAD

**Issue by nitha26** [nextstrain/conda#9]
Hi,
I am trying to install Nextstrain in centos7. I get following error when i give this ``conda env create -f nextstrain.yml``

``Pip subprocess error:  
    ERROR: Command errored out with exit status 1:  
     command: /root/miniconda3/envs/nextstrain/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3rpz1v64/snakemake/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3rpz1v64/snakemake/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yfakhxf0
         cwd: /tmp/pip-install-3rpz1v64/snakemake/  
    Complete output (2 lines):  
    At least Python 3.7 is required.     
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.  
failed  
CondaEnvException: Pip failed``

default i have python version 3.8

``Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux``

Thanks

**Comment by huddlej** [comment]
Hi @nitha26, thank you for reporting this issue. PR #10 should have resolved this issue, but would you mind repeating your installation of the Nextstrain environment to confirm that it is working now?
